inherit_from: .rubocop_autoexclusion.yml

Metrics/MethodLength:
  Max: 7
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Style/Documentation:
    Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false