source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'bootsnap', require: false
gem 'devise', '~> 4.2'
gem 'jsonapi-serializer'
gem 'pg', '~> 1.3.5'
gem 'rack-cors'
gem 'rails', '~> 7.0.4'
gem 'redis-rails', '~> 5.0.2'
gem 'sidekiq', '~> 6.4.2'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'unicorn', '~> 6.1.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 4.0'
  gem 'rubocop', require: false
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  gem 'shoulda-matchers'
end
